# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80b8fefd204fdb833a35695a7ffe7f8d4055fe5fb19c329a50739d6d6c276011384f3651751fa47c3039d6397bafdff11164cc5142c49fcf31ce1a73693e09cc

test:
  secret_key_base: 50b5733b626faf7ce78a0afa86a5f76cd36492505e5c617142716df4b496c2e0f47f62aec6815e36fe6e9d1f153a64fb8e668519aa376cf1b8fe069d59a3a5b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
